Removal NameFieldLabel. Change "Open" to "File"
migueldeicaza/gui.cs pull request #1006
Opened 2020-11-15 18:41 UTC by SemperFu

I noticed the SaveDialog used Open for the filename. 

The NameFieldLabel was hardcoded and ignoring the value passed by the OpenDialog and SaveDialog

![Save1](https://user-images.githubusercontent.com/1786698/99193546-be12da80-2747-11eb-9dfd-02936e59d5cd.png)

At first I changed it to use the passed fields but it doesn't really make since with Open and Save as the file name. The buttons at the bottom are Open and Save. 

![Save2](https://user-images.githubusercontent.com/1786698/99193585-fe725880-2747-11eb-8218-df111f362323.png)

The top field is the directory and the bottom is the filename it self. I think it would make sense to name it "File" or "Filename" like Directory. 
![File1](https://user-images.githubusercontent.com/1786698/99193598-12b65580-2748-11eb-96b8-a44bf711ce5e.png)
![File2](https://user-images.githubusercontent.com/1786698/99193601-15b14600-2748-11eb-9ae5-ae09fb8097d3.png)
![Word](https://user-images.githubusercontent.com/1786698/99193603-1813a000-2748-11eb-8faf-bb32abe43be9.PNG)

This matches normal FileDialogs as well. So if this would stay hard coded I just removed the the input fields from the Open and SaveDialogs all together.

2020-11-17 15:59 UTC, tig requested changes
I think this is a breaking API change as you've coded it, right? Existing code that tries to use `nameFieldLabel` will no longer build. 

Did you check to see if this breaks any existing apps?

2020-12-09 16:41 UTC, migueldeicaza commented
Good point, I would introduce a new constructor/API with the additional parameter.

Alternatively, this could be a property that is set after it has been created, not something that must be passed during construction.

2020-12-10 03:26 UTC, SemperFu commented
Sorry I missed the first response, yes it would be a breaking change for someone who uses filedialog directly but it would not break Save and Open Dialogs. I did leave the ability to set the property after the creation. The problem is you can only have 4 chars based on how the window is built, it doesn't take into account the number of chars to position it. 

I can add modify the pull for an additional constructor this weekend.

2021-02-15 17:14 UTC, tig commented
> Sorry I missed the first response, yes it would be a breaking change for someone who uses filedialog directly but it would not break Save and Open Dialogs. I did leave the ability to set the property after the creation. The problem is you can only have 4 chars based on how the window is built, it doesn't take into account the number of chars to position it.
> 
> I can add modify the pull for an additional constructor this weekend.

Hey @SemperFu , did you get  a chance to make the requested changes?

2021-04-01 17:23 UTC, BDisp commented
This was already fixed on PR #1157 with the option to the derived class now can choose the both label names.

2021-04-01 17:27 UTC, closed without merging