Cursor shape and visibility
migueldeicaza/gui.cs pull request #1102
Opened 2021-01-28 16:43 UTC by G-Freart

Hello,

This pull request contains a fix for issues #905 and #280

It has been tested under Linux (CentOS 8 Stream, Ubuntu 20.04) in Gnome Terminal and also in real TTY.
It works also under Windows. 

Under XTerm, the amount of cursor possibilities are more important than under TTY. The documentation 
related to the CursorVisibility enumeration describe it.

In order to test the different possibility, a dynamic menu will appear within the Editor Scenario.

I was not able to make it working with System.Console. 
May be due the set of customization this code already have. 
Even, if it was working which is not the case, the 'native' method work only under Windows.

As i don't have a MacOS i could not test this PR under this Operating Systems.

Best Regards,
Gilles Freart

2021-01-29 11:34 UTC, BDisp commented
Really good job. Thanks. I think that selecting the entire character initially can cause the impression that the capslock is on and confuse the user. Wouldn't it be possible to put a narrower width if the capslock is turned off?
In the case of `NetDriver`, perhaps the best solution would be through `Virtual Terminal Sequences` but he is not yet ready to process it and would be grateful for all the possible help for the possibility of improving it. Unfortunately, `System.Console` still does not work the same way on both systems (`Windows` and `Unix`) and I had to activate the escape sequences by creating the console with native `Windows APIs` and some of the `System.Console APIs` are not compatible with `Unix`. As a last resort, for Windows a possible implementation of cursor visibility would perhaps be the solution you implemented on `WindowsDriver` but for `Unix` it would have to be escape sequences and some native Unix library, other than `NCurses`. But if there is a common solution it would be better. Any idea?

2021-01-29 15:33 UTC, migueldeicaza requested changes

2021-01-29 15:33 UTC, migueldeicaza commented on Terminal.Gui/ConsoleDrivers/CursesDriver/CursesDriver.cs
> +			}
Let us follow the coding style, statements should be in different lines, and we should remove the additional space

2021-01-29 15:33 UTC, migueldeicaza commented on Terminal.Gui/ConsoleDrivers/CursesDriver/CursesDriver.cs
> +			if (!currentCursorVisibility.HasValue) {
Style - generally, in this codebase I do not use braces for single statements.

2021-01-29 15:33 UTC, migueldeicaza commented on Terminal.Gui/ConsoleDrivers/CursesDriver/CursesDriver.cs
> +			}
Braces should open on the same line as the "if"

2021-01-29 15:33 UTC, migueldeicaza commented on Terminal.Gui/ConsoleDrivers/WindowsDriver.cs
> +				var err = Marshal.GetLastWin32Error ();
Let us eliminate white space lines

2021-01-29 15:33 UTC, migueldeicaza commented on Terminal.Gui/ConsoleDrivers/WindowsDriver.cs
> +
I see what is going on here, but let us stick to the coding style we use here, each`visibility = XX` needs to go on its own line.

2021-01-29 15:33 UTC, migueldeicaza commented on Terminal.Gui/Views/TextField.cs
> +		{
Let us replace "Wished" with "Desired"

2021-01-29 15:33 UTC, migueldeicaza commented on UICatalog/Scenarios/Editor.cs
> +			List<MenuBarItem> menuBarItems = new List<MenuBarItem> (
Gratuitous reformatting, please keep the original style

2021-01-29 16:31 UTC, G-Freart commented
> Really good job. Thanks. I think that selecting the entire character initially can cause the impression that the capslock is on and confuse the user. Wouldn't it be possible to put a narrower width if the capslock is turned off?

Thanks

I have search after a way to known the capslock state but i found nothing direct . What i have seen under linux is to connect to the X11 if any display is available and get the led status as we could get using the shell command 'xset -q' but it's far from a nice solution as we could have user connected using ssh and without X11 connected !

I have change the cursor displayed to the CursorVisibility.Default so under xterm, it will use the setinngs set by the user, and if not under xterm, it will use the underline. Under windows, the cursor will be underline as not under an xterm.

2021-01-29 17:08 UTC, G-Freart commented
Hello Miguel,

Don't hesitate to tell me if they are anything else or if more re-styling must be done.

Best Regards,
Gilles Freart

2021-01-29 18:34 UTC, BDisp commented
I was never able to make capslock work on `Linux`. He really needs a Display to work. But if you managed to make it work, having a `Display` is better than nothing. An example I can give about the uncertainty that capslock may or may not be activated, is in the `TextField` where if it is activated, the character under the cursor is printed with the inverted color looking like the cursor blinking, but without blinking. In my opinion if the `capslock` is off, it is better to leave the cursor underlined, in cases where its visibility is true.

2021-01-30 11:25 UTC, BDisp approved these changes

2021-02-06 10:18 UTC, G-Freart commented
Hello @migueldeicaza ,

Something is missing ?

Best Regards,
Gilles Freart

2021-02-11 05:39 UTC, Bonny40 commented
Ich bin neu hier 
Hallo zusammen 
Ich brauche hilf ich habe Probleme mit mein Handy ich glaube Hecker ist hinter mir her

2021-02-15 17:13 UTC, merged

2021-02-15 17:54 UTC, tlemmons commented
I am not sure if this is related.  I cannot see the cursor in a dialog->text field unless it is on a character.  Being in empty space (after any characters) it is invisible.  I have pulled current but no change.  Is there some setting I am missing for this?