Feature #23 Feature TextMaskField
migueldeicaza/gui.cs pull request #1215
Opened 2021-04-17 11:15 UTC by jmperricone

![mask](https://user-images.githubusercontent.com/4634030/115109799-4ba06380-9f4e-11eb-8031-b587861a7a5b.gif)

Features:
- Mask
  - Mask char can by changed. Default : ( _ ).
  - Charset
    - 0 : Number (Required)
    - 9 : Number
    - L : Letter (Required)
    - ? : Letter
    - A: Alphanumeric (Required)
    - a: Alphanumeric
  - Each character has an associated regex. When the field is generated, it joins everything together and compiles it.
  - On input use the regex of the char to accept the input, and after input use the joined regex to validate the field.

- Regex
  - Pattern matching, validating on input.

- TextAlignment
  - Left
  - Centered
  - Right
  
- Events
  - TextChanged
  - OnValidating

- Keys
  - Left
  - Right
  - Home
  - End
  - Delete
  - Backspace

Issue #23 

**Hope you like it!**

2021-04-17 11:41 UTC, BDisp commented
That's really great. Thanks.

2021-04-17 13:15 UTC, jmperricone commented
![mask2](https://user-images.githubusercontent.com/4634030/115114311-fde32580-9f64-11eb-9cf9-3b7c599d9d2b.gif)

Added **bool RegexValidateInput** .  
Setting it to false validates after input.. allowing any input.

Use **bool IsValid** to check.

2021-04-17 13:21 UTC, BDisp commented
Amazing.

2021-04-18 17:16 UTC, tig requested changes
This is an AWESOME new capability. Thank you so much for doing it and contributing. 

Most of my comments are just nits, you've done a great job keeping this clean and smiple. It does just want it needs to and no more. I really appreciate that you provided some obvious "no code" built-in functionality AND provided the ultra-powerful regex capability. Well done.

The `Terminal.Gui` project is still woefully weak in unit tests and I'm on mission to push folks to change that. I think you've done the bare minimum here and want to challenge you to raise the bar as a demonstration to other contributors (including me!) of how it should really be done. Are you up for it?

2021-04-18 17:16 UTC, tig commented on UnitTests/TextMaskFieldTests.cs
> +			Assert.False (_textMaskField_Regex.IsValid);
Seems to me a few more tests to exhaustively prove you are filtering bad (dangerous?) regex might be in order.

2021-04-18 17:16 UTC, tig commented on Terminal.Gui/Views/TextMaskField.cs
> +		};
What if I wanted a field that only accepted non-alpha and non-numeric characters? e.g. `@#$%^&*`.

I suppose I could use a regex?

2021-04-18 17:16 UTC, tig commented on Terminal.Gui/Views/TextMaskField.cs
> +		public override void PositionCursor ()
It is not immediately obvious what you are doing here. If it were me, I'd creates some unit tests that clearly show intent (and ensure intent doesn't break).

2021-04-18 17:16 UTC, tig commented on Terminal.Gui/Views/TextMaskField.cs
> +		bool DecCursorPosition ()
Add unit test?

2021-04-18 17:16 UTC, tig commented on Terminal.Gui/Views/TextMaskField.cs
> +		bool IncCursorPosition ()
Add unit test?

2021-04-18 17:16 UTC, tig commented on Terminal.Gui/Views/TextMaskField.cs
> +		void BackspaceKeyHandler ()
Add unit test?

2021-04-18 17:16 UTC, tig commented on Terminal.Gui/Views/TextMaskField.cs
> +		void DeleteKeyHandler ()
Add unit test?

2021-04-18 17:16 UTC, tig commented on Terminal.Gui/Views/TextMaskField.cs
> +		void CompileMask ()
If it were me, I'd add a big unit test for this and challenge myself to feed it at least a dozen test cases. Some with just random jibberish. Some with intentional boundary cases. Etc... A lot could go wrong here with someone mucking with this code someday.

2021-04-18 17:16 UTC, tig commented on UnitTests/TextMaskFieldTests.cs
> +﻿using Xunit;
Kudos for these tests.

2021-04-18 17:27 UTC, tig commented on Terminal.Gui/Views/TextMaskField.cs
> +		protected TextMaskField ()
I believe this needs to be public. We require all `View` classes to have a parameterless public constructor.

Like this

![image](https://user-images.githubusercontent.com/585482/115154584-795dd900-a030-11eb-887a-5aaa4d87ab2f.png)

Without this `AllVeiwsTester` crashes.

I think all unit test suites should have tests for each constructor, FWIW.

2021-04-18 17:28 UTC, tig requested changes
Crashes `AllViewTester`

2021-04-18 17:43 UTC, tig commented
I changed the Scenario code to this and it did not work as I expected:

![image](https://user-images.githubusercontent.com/585482/115154745-48ca6f00-a031-11eb-8bf0-3053afb62a0b.png)

And the app crashes if you attempt to type after doing this. 

I then did this and, again, was surprised with the result:
![image](https://user-images.githubusercontent.com/585482/115154879-f9d10980-a031-11eb-9c9f-c23e8ae55c09.png)

I think it's debatable whether setting the `Text` property should work exactly as if the user typed the contents, or if the caller has to "pre-compiled" the result.

Likewise, getting the value of the `Text` property COULD return exactly what the customer typed or the "compiled" result.

Can you explain why you chose to do it they way you did? I think there are probably valid reasons for doing it either way but I'm not convinced which should be default/primary. 

I note that .NET's version of this takes the approach you took: 

https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.maskedtextbox?view=net-5.0

FWIW, I also noticed that .NET provides a nice primitive that we COULD leverage (not saying we should, just ensure you are aware of it).

https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.maskedtextprovider?view=net-5.0

2021-04-18 18:33 UTC, jmperricone commented on Terminal.Gui/Views/TextMaskField.cs
> +				// TODO: Implement logic to match non-perfect inputs (mask == text)
### What I meant by TODO was more of a proposal to improve if necessary.

Type Mask:
When an initial value is provided, it is validated with the mask 1:1.
Example:
```
        mask = "(000-9000)" // 0 (required) , 9 (optional)
```

Some cases (of course there are many more cases)
```
	input1 = "(123-4567)" // OK
	input2 = "(123- 567)" // OK
	input3 = "(123-456)"  // FAIL
	input4 = "123- 456"   // FAIL
	input5 = "123-456"    // FAIL
	input6 = "123456"     // FAIL
	input7 = "1234567"    // FAIL
```

This is the basic (current) implementation. 
	
```
       if (Validate (text) == false) {
           text = new List<Rune> ();
       }
```


I think that some of those cases for example should be valid and others not, but I find it difficult to find a validator that is logical for everyone and not only for the one who implemented it.

Now, the chances of validating something wrong as correct is zero with the current implementation.

2021-04-18 20:38 UTC, jmperricone commented
Hi tig

I saw that net provider and many more implementation but I thought about implementing this by my self.
Of course I can try to plug that provider if you think its a better option.

2021-04-18 20:53 UTC, tig commented
> Hi tig
> 
> I saw that net provider and many more implementation but I thought about implementing this by my self.
> Of course I can try to plug that provider if you think its a better option.

I think your implementation is awesome. I just wanted to make sure you were aware of it.

2021-04-19 18:39 UTC, jmperricone commented
Hi Tig, I reimplemented the whole thing around the same base. How do you want to do?
I can commit to this pull or make a new pull request ?

2021-04-19 18:44 UTC, jmperricone commented
Ok!

2021-04-25 17:37 UTC, tig commented
Closing. Dupe of #1230

2021-04-25 17:37 UTC, closed without merging