Feature TextValidateField
migueldeicaza/gui.cs pull request #1230
Opened 2021-04-20 01:26 UTC by jmperricone

Hi. I explain what I did.

```csharp
public class TextValidateField<T> : View where T : ITextValidateProvider
```
We create the view specifying a provider that implements `ITextValidateProvider`.

```csharp
public interface ITextValidateProvider {
			bool Fixed { get; }
			int CursorLeft (int pos);
			int CursorRight (int pos);
			int CursorStart ();
			int CursorEnd ();
			bool Delete (int pos);
			bool InsertAt (char ch, int pos);
			bool IsValid { get; }
			ustring Text { get; set; }
			ustring Mask { get; set; }
		}
```

I made 3 providers.

```csharp
public class NetMaskedTextProvider : ITextValidateProvider {} // .Net MaskedTextProvider  👍 
public class TextMaskProvider : ITextValidateProvider {} // My version of a Masked Input using Regex.
public class TextRegexProvider : ITextValidateProvider {} // Validates with Regex
```
Example use with NetMaskedTextProvider.
[Microsoft MaskedTextProvider Documentation](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.maskedtextbox.mask?view=net-5.0) Here are all the masking characters.
```csharp
var netProviderField = new TextValidateField<NetMaskedTextProvider> ("999 000 LLL >LLL AAA aaa") {
        X = 0
        Y = 0
};
Win.Add (netProviderField);
```
I have not done any tests yet, I want to know if we are on track.
Let me know what you think.
Round 2.

2021-04-20 03:44 UTC, tig commented
This is so much fun. What an awesome idea to make it extensible like this.

I'll take a closer look as soon as I get a chance!

2021-04-20 21:24 UTC, tig commented
Suggest you mark this as a draft PR until you have unit tests etc....

Ok?

2021-04-21 09:35 UTC, jmperricone commented
Hi, I want to add mouse tests. I need the width to be setted, to test with text alignment center and right.
Can this be done ?

2021-04-21 09:40 UTC, jmperricone commented
@tig  What do you think if we take out the mask provider I made, because it doesn't make sense to have both now.
Maybe save it as an example somewhere.

2021-04-25 17:21 UTC, tig commented
> @tig What do you think if we take out the mask provider I made, because it doesn't make sense to have both now.
> Maybe save it as an example somewhere.

I will leave the decision on that to you, sir!

2021-04-25 17:36 UTC, tig requested changes
Just a few nits that I'd like you to address before I merge... 

This is all really great work!

2021-04-25 17:36 UTC, tig commented on UnitTests/TextValidateFieldTests.cs
> +			} catch (RegexParseException ex) {
Please fix all build warnings.

2021-04-25 17:36 UTC, tig commented on UnitTests/TextValidateFieldTests.cs
> +namespace Terminal.Gui {
Change namespace to `Terminal.Gui.Views`.

2021-04-25 17:36 UTC, tig commented on UnitTests/TextValidateFieldTests.cs
> +﻿using System.Diagnostics;
Nice job!!

NetMaskedTextProvider - 85.4% Code Coverage
TextMaskProvider - 57.3%
TextRegExProvider - 81.9%
TextValidateField - 85.4%

Really impressive work! Thank you.

2021-04-25 19:13 UTC, tig approved these changes

2021-04-25 19:13 UTC, merged

2021-04-25 19:14 UTC, tig commented
Woot! Merging!