Fixes #1502. Prevents high CPU usage.
migueldeicaza/gui.cs pull request #1504
Opened 2021-11-01 22:56 UTC by BDisp

2021-11-13 15:45 UTC, tig requested changes

2021-11-13 15:51 UTC, BDisp commented on Terminal.Gui/ConsoleDrivers/NetDriver.cs
> +				Thread.Sleep (10);
I agree. Done. Thanks.

2021-11-15 07:04 UTC, tznind commented
Should this be user configurable? i.e. a static property on the NetDriver class? Something like `WaitWinChangePollTimer`? That at least empowers developers to adjust it based on system settings/hardware or desired refresh times or whatever?

2021-11-15 10:09 UTC, BDisp commented
@tznind `NetDriver` is internal, like `WindowsDriver` and `CursesDriver`, with the exception of `FakeDriver` for unit test. So, it must doed in the `Application`, but only for `NetDriver`, like the `AlwaysSetPosition` property, which I don't like.
In my opinion this setting is enough, so no much low and not making much difference and no much high and give time enough to detect any windows resize. If anyone more expertise can come with a better and appropriate solution, can submit a PR before or after this PR.

2021-11-15 10:12 UTC, tznind commented
Cool, that sounds like a solid reason not to make it user configurable and that you have thought about it.   So I am happy :)

2021-11-25 12:26 UTC, TETYYS commented
virtual medal to whoever releases this fix

2021-12-18 13:22 UTC, tig approved these changes
LGTM. Great work.

2021-12-18 13:22 UTC, merged