Fix MoveUp and MoveDown to prevent exception
migueldeicaza/gui.cs pull request #891
Opened 2020-09-06 18:09 UTC by Mgamerz

When calling MoveUp and MoveDown, the 'selected' variable is not checked. If I am using a backing data source that can change, this selected value +/- 1 may still not lie in the valid range of values. This PR checks and changes the following:

1) If moving up, and the CURRENT selected value is >= backing data length, the last item is selected
2) If moving down, and the CURRENT selected value is >= backing data length, the last item is selected
3) If the items list has no items, the methods return false as there is nothing to move to. I'm not sure if we should set lastSelectedItem to -1 in this instance.

2020-09-09 19:29 UTC, tig requested changes
Please fix the formatting. Thanks.

2020-09-10 05:01 UTC, Mgamerz commented
Fix the formatting.

2020-09-17 19:02 UTC, Mgamerz commented
Added a commit to fix pressing enter on an empty list throwing an exception.

2020-09-18 13:01 UTC, BDisp commented
@Mgamerz I think you have to fix the formatting again :-)

2020-09-26 23:51 UTC, tig commented
Closing as I've replaced it with https://github.com/migueldeicaza/gui.cs/pull/906

2020-09-26 23:51 UTC, closed without merging